require "./src/ui/panels/form.rb"
require "./src/ui/panels/search.rb"
require "./src/ui/elements/box.rb"
require "./src/ui/elements/text.rb"
require "./src/ui/elements/field.rb"
require "./src/ui/elements/button.rb"